### ISSUE TITLE
Create yml file to define pythoncritic configurations

### ISSUE THREAD

**Issue by caiohenrique12** [caiohenrique12/pythoncritic#4]
We need to create a `pythoncritic.yml.sample` (feel free to improve) containing some particular configurations from black, pytest, flake8, and coverage. Which this option, the user defines the constraints for your project. 

Example:

`$ pythoncritic/.pythoncritic.yml.sample`
```
pythoncritic:
   - source_path_project: []

flake8:
    - max_line_length: 100

coverage:
   - precision: 100

```
